/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Password needed");
gchar *s = N_("_Run");
gchar *s = N_("<span weight=\"bold\">The requested action needs superuser (root) privileges.</span>\n"
              "Please enter the superuser password and click Run to continue.");
gchar *s = N_("Superuser _password:");
gchar *s = N_("*");
gchar *s = N_("Command to run:");
gchar *s = N_("<span style=\"italic\" weight=\"bold\">Please wait, verifying password...</span>");
